### PR TITLE
Update init.qcom.rc

### PR DESCRIPTION
**Pull request by ghost**
Disable cnss_diag unnecessary logging to /sdcard/wlan_logs

### CODE REVIEW

**Review by xyyx — COMMENTED** [review]
Hmm. I don't have wlan_logs

**Comment by ghost** [comment]
wlan folder is present on my internal storage (Mi Max - Hydrogen).

2017-02-19 20:14 GMT-03:00 Max <notifications@github.com>:

**Comment by xyyx** [comment]
Strange. It has oneshot.

**Comment by xyyx** [comment]
Will make it as in Bullhead

**Pull request closed without merging**
